function fct = stopCritMaxIterEpsilonCreator(M,maxIter, epsilon)
% stopCritMaxIterEpsilonCreator(M,maxIter,epsilon)
% Cearet a stopping Criterion function for a maximal number of iterations
%   or a minimal maximal change, whichever hits first.
%
% INPUT
%   M      : the manifold the data lives on
%  maxIter : the maximal number of iterations
% epsilon  : the maximal change within an iteration
% ---
% MVIRT 1.1 | R. Bergmann | 2018-01-25
fct = @(x,xold,~,iter) ...
    (max(M.dist(...
        x(M.allDims{:},...
            reshape(any(reshape(~isnan(xold)&~isnan(x),prod(M.ItemSize),[]),1),[],1)...
        ),...
        xold(M.allDims{:},...
            reshape(any(reshape(~isnan(xold)&~isnan(x),prod(M.ItemSize),[]),1),[],1)...
        )...
        )) < epsilon ...
    || (iter > maxIter) ) && iter>1 && ~isnan(any(x(:))) && ~isnan(any(xold(:)));
end

